services:
  web:
    build: .
    container_name: cluster-webapp
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: cluster_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: cluster_db
      MYSQL_USER: ann
      MYSQL_PASSWORD: ann123
    volumes:
      - cluster_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  cluster_mysql_data: